version: "2"

services:
  postgres:
    image: postgres:latest
    container_name: postgreSQL
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: xxpassxx
      POSTGRES_USER: db_user
      POSTGRES_DB: pizza
